### ISSUE TITLE
All Ores Smelt to Molten Corruption in Tinkers Smletery 1.0.7-10

### ISSUE THREAD

**Issue by crazyirishwrencher** [TehNut-Mods/Soul-Shards-Respawn#11]
Any ore smelts ultra fast into a "corrupted" form of molten corruption. I can smelt it into anything. Rolling back to prev version returns normal function, but leave bugged fluid in tank.

**Comment by TehNut** [comment]
Can you try with this version? 

https://waifu.me/file/SoulShardsRespawn-1.12.2-1.0.7-CUSTOM.jar

**Comment by crazyirishwrencher** [comment]
That version fixes it.

**Comment by TehNut** [comment]
Thanks. I'll push a new build when I get home.
