### ISSUE TITLE
[Compatibility] Differentiate between Chickens mod cluckers

### ISSUE THREAD

**Issue by herobrine150400** [TehNut-Mods/Soul-Shards-Respawn#12]
Well, I was playing with this mod, and the mod "Chickens", and I noticed that if you use a soul shard on a chicken from that mod (for example a platinum chicken (from its addon, More Chickens)), and use that shard in a spawn cage, the cage will spawn random chickens (like sand and flint chickens) instead of the platinum chickens themselves.

This probably happens because the shard only registers the ID of the entity, and all the chickens from that mod have the same ID ("chickens:chickenschicken"), they only differ in an NBT tag named "Type", and as the shards don't save NBT, they can't know the correct type of chicken.

My suggestion is to add an option in the config file, inside the "compat" tab for Chickens, which would be like "B:savechickentype=true".

Which would save the "Type" NBT from the chicken into the shard's own NBT, allowing the cage to differentiate the types of chicken and spawn them correctly.

Oh, and also, as a consequence of the shard not saving that NBT tag, any tipe of chicken killed from that mod will be added into the number of souls in the shard, even if from different types.

**Comment by TehNut** [comment]
I'll take a look, but I don't really have anything in place to handle this anymore. MC 1.12+ frowns on having sub entities like this.
