### ISSUE TITLE
Broken Enchantments

### ISSUE THREAD

**Issue by ordzai** [TehNut-Mods/Soul-Shards-Respawn#13]
After deleting SS-TOW from my server, and installing SS-Respawn, it seems the enchantments are blank enchanted books from vanilla minecraft (in JEI).  The soul stealer enchants don't seem to be craftable in any way.  Booting up the new server meant having to run the /fml confirm command about missing items, but there weren't many errors after a restart.
![image](https://user-images.githubusercontent.com/1112830/48964883-0511cf00-ef77-11e8-8952-fbef0e2699a6.png)

**Comment by TehNut** [comment]
Were there any errors at startup? You could try loading up without SS at all once, running` /fml confirm`, then re-adding SS. I'm not really sure what else could be done about this.

**Comment by ordzai** [comment]
Did as you suggested and now they have proper descriptions, thank you.  They are not craftable, however, but that may be intended? I have not tried to get them randomly through the normal enchanting mechanic.

**Comment by TehNut** [comment]
I don't remember the enchantment being craftable before. Pretty sure it was just from the enchantment table
