### ISSUE TITLE
allowFakePlayers not counting Turtles

### ISSUE THREAD

**Issue by Savag3life** [TehNut-Mods/Soul-Shards-Respawn#17]
I assume this setting means that turtles should be able to level up a soul shard.

**Comment by TehNut** [comment]
This means that turtles are not proper fake players. The check is literally just `instanceof FakePlayer`. https://github.com/TehNut/Soul-Shards-Respawn/blob/1.12.2/src/main/java/info/tehnut/soulshardsrespawn/core/EventHandler.java#L41

**Comment by Savag3life** [comment]
So what would that be for? I can't seem to find any kind of `Fake Player` killing tool. At least none that support and inventory to store the shard. If you could just point me in the direction of the mod that this function was intended for, I'll be all set.

**Comment by Savag3life** [comment]
Additionally, could I suggest adding turtle support?

**Comment by TehNut** [comment]
The function is intended for any mod using a proper FakePlayer. I don't know any off the top of my head. I don't plan to add specific CC support.
