### ISSUE TITLE
Enchantments duplication when using SSR in pair with Rough Mobs 2

### ISSUE THREAD

**Issue by Onigeshi** [TehNut-Mods/Soul-Shards-Respawn#18]
Rough Mobs 2 adds enchanted gear to the mobs, for some reason, mobs spawned using SSR spawner, get their enchants duplicated like so http://prntscr.com/moabe4 ... now im not sure which mod is at fault, SSR or Rough Mobs, but im gonna report it here first..

**Comment by TehNut** [comment]
There is nothing special in my spawning code. You should report this to the other mod.

**Comment by TehNut** [comment]
Fixed with https://minecraft.curseforge.com/projects/rough-mobs-2/files/2691626 (https://minecraft.curseforge.com/projects/rough-mobs-2/issues/37)
