### ISSUE TITLE
items keeps duplicating in ae2 terminal

### ISSUE THREAD

**Issue by niklas2233** [TehNut-Mods/Soul-Shards-Respawn#19]
when you put soul shards in an applied energistic system they keep duplicating but you cant take them out so it keep making ghost items in the terminal

mc version 1.12.2

**Comment by TehNut** [comment]
I'm not sure what AE is doing to cause this. The items themselves are extremely simple and just hold some NBT data. AE is too much of a mess inside for me to want to look any farther.
