### ISSUE TITLE
Tier 1 Soul Cage not checking for light or players

### ISSUE THREAD

**Issue by TheIllusiveC4** [TehNut-Mods/Soul-Shards-Respawn#2]
#### Observed Behavior
Using a tier 1 skeleton soul shard in a soul cage, the skeletons continue spawning regardless of light level or player presence.

#### Expected Behavior
Using a tier 1 skeleton soul shard in a soul cage, the skeletons will only spawn when a player is nearby and the light level is sufficiently low enough to allow spawning.

#### Steps to Reproduce
1. Make sure the config settings for tier 1 are set to true for "checkLight" and "checkPlayer"
2. Place a soul cage
3. Light up the surrounding area so that the light level is greater than 8 on all blocks
4. Place a tier 1 soul shard bound to skeletons into the soul cage
5. Stand 50 blocks away from the cage
6. Observe the spawning behavior
-----
#### Versions
Soul Shards Respawn: 1.12.2-1.0.2-4
Minecraft: 1.12.2
Forge: 14.23.3.2673

**Comment by TehNut** [comment]
Who has two thumbs and is an idiot?

![](https://i.imgur.com/l6Wd0SL.gif)

**Comment by TehNut** [comment]
I was checking the position of a newly constructed entity for the light check, which is *obviously* wrong. I didn't even have the check for players because I'm smart.
