### ISSUE TITLE
Crash when next to a door

### ISSUE THREAD

**Issue by Serifina** [TehNut-Mods/Soul-Shards-Respawn#20]
A Soul Cage, next to Minecraft wooden door, causes a crash whenever the chunk loads.

https://gist.github.com/Serifina/8801854f043562d52b032b1e3c25ad9c

**Comment by TehNut** [comment]
Should be solved by https://github.com/TehNut/Soul-Shards-Respawn/commit/47149bcca21ac61dfc6523b11e1b7c28379cd365
