### ISSUE TITLE
[Crash] Enchanting a sword with Soul Stealer

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/Soul-Shards-Respawn#23]
Im trying to enchant an Emerald Sword(Cyclic) with Soul Stealer 3 but I get the following crash:
https://paste.gg/p/anonymous/b0f5ed2b426040df89c3dace35b2f874

**Comment by TehNut** [comment]
Does it happen with any sword? Does it happen with only Soul Shards installed?

**Comment by TehNut** [comment]
I am unable to reproduce this is in dev. I can only assume some mod is coremodding into `isCompatibleWith` and doing something wrong..

**Comment by ghost** [comment]
Tested it too and can approve that some other mod seems to be the problem - Ill try some mods and see which one it could be.

**Comment by ghost** [comment]
Ok so seems like it only happens in one specific world of mine.

**Comment by TehNut** [comment]
That's... very strange. There's nothing in that method that should NPE... Have you removed any mods that included enchantments in the past?

**Comment by ghost** [comment]
I remember now I just had another enchantment on it which has not been shown but I could see it in the NBT data

**Comment by ghost** [comment]
@TehNut anyway which Tier do I need to spawn mobs in another dimension - its not stated on the project page https://minecraft.curseforge.com/projects/soul-shards-respawn?gameCategorySlug=mc-mods&projectID=291549

**Comment by TehNut** [comment]
There's no dimension checks in this version. I may add it in the future, but it's very hard to do the detection for that with mods.

**Comment by ghost** [comment]
So I need to spawn them in their own dim?

**Comment by TehNut** [comment]
You can spawn anything in any dimension. The check simply isn't there. If something is stopping an entity from being spawned, that's being done by another mod.
