### ISSUE TITLE
1.14.3 crash on start works in 1.14.2 with same mod set

### ISSUE THREAD

**Issue by MrPurple6411** [TehNut-Mods/Soul-Shards-Respawn#25]
`---- Minecraft Crash Report -------- Minecraft Crash Report ----// Would you like a cupcake?
Time: 6/8/19 1:13 PMDescription: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors! at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45) at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34) at net.minecraft.class_310.method_1503(class_310.java) at net.minecraft.class_310.method_1514(class_310.java:395) at net.minecraft.client.main.Main.main(Main.java:154) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) at org.multimc.EntryPoint.listen(EntryPoint.java:143) at org.multimc.EntryPoint.main(EntryPoint.java:34) Suppressed: java.lang.NoSuchMethodError: net.minecraft.class_1928.method_8354()Ljava/util/TreeMap; at info.tehnut.soulshards.SoulShards.onInitialize(SoulShards.java:31) at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38) at java.util.ArrayList.forEach(Unknown Source) at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36) ... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Client threadStacktrace: at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45) at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34) at net.minecraft.class_310.method_1503(class_310.java)
-- Initialization --Details:Stacktrace: at net.minecraft.class_310.method_1514(class_310.java:395) at net.minecraft.client.main.Main.main(Main.java:154) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) at org.multimc.EntryPoint.listen(EntryPoint.java:143) at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- System Details --Details: Minecraft Version: 1.14.3 Pre-Release 2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_211, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 487854216 bytes (465 MB) / 1771044864 bytes (1689 MB) up to 3817865216 bytes (3641 MB) JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m Fabric Mods:  alwaysdroploot: Always Drop Loot 3.5.0+mc1.14.1 anvil_fix: AnvilFix 1.1.2 appleskin: AppleSkin 1.0.6 autoconfig1: Auto Config v1 1.1.2+mc1.14.1 autofish: Autofish 0.8.4 betterutilities: Better Utilities 1.4.1 blue_endless_jankson: jankson 1.1.2 brighter: Brighter 1.0.0 cloth: Cloth Events 0.3.1+build.23 cloth-config: Cloth Config 0.2.4+build.17 cloth-config2: Cloth Config v2 0.1.0 composableautomation: Composable Automation 0.5.0+mc1.14.2 couplings: Couplings 1.0.0 craftingpad: Crafting Pad 1.0.3 crochet: Crochet 1.0.4 cursedchests: CursedChests 2.3.21 darkelevators: Elevators 1.1.3 dbag: Death Bag 1.14-Pre5-5.1 dumpster: Dumpster 0.3.0 easierchests: EasierChests 1.14-fabric0.2.7-1.3.1 extra-pressure-plates: Extra Pressure Plates 1.1.2 fabric: Fabric API 0.3.0+build.179 fabric-api-base: fabric-api-base 0.1.0+59147463 fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52 fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52 fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8 fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463 fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463 fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463 fabric-furnaces: Fabric Furnaces 1.1.4 fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463 fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+59147463 fabric-language-kotlin: Fabric Language Kotlin 1.3.31+build.4 fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463 fabric-models-v0: fabric-models-v0 0.1.0+59147463 fabric-networking: fabric-networking 0.1.0+93af775a fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52 fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2 fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882 fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.1+4d26f9ba fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b fabric-renderer-indigo: fabric-renderer-indigo 0.1.5+f8c32967 fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2 fabric-rendering-v0: fabric-rendering-v0 0.1.0+59147463 fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463 fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+59147463 fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35 fabricloader: Fabric Loader 0.4.8+build.154 fermion: Fermion 0.6.0+build.29 gbfabrictools: GBfabrictools 1.0.1 harvest: Harvest 1.0.4 iamverysmart: I Am Very Smart 1.4.0+mc1.14.1 infinityfix: Infinity Fix 1.0.4 leveluphp: Level Up HP 4.3.0+mc1.14.2 libblockattributes: LibBlockAttributes 0.4.2 malilib: MaLiLib 0.9.6 mbackpacks: Mpcs' Backpacks 1.1.4 modmenu: Mod Menu 1.6.2-92 moenchantments: Mo'Enchantments 1.5.8 notenoughwands: Not Enough Wands 1.7.5.beta org_jetbrains_annotations: annotations 16.0.3 org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.31 org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.31 org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.31 org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.1 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.1 peacefulsurface: PeacefulSurface v3a-fabric redstonebits: Redstone Bits 1.0.4+mc1.14.1 redstonetweaks: Redstone Tweaks 1.0.2 roughlyenoughitems: Roughly Enough Items 2.9.4+build.128 simple_pipes: SimplePipeTest 0.1.5 simpleteleporters: Simple Teleporters 2.1.0 smoothbedrock: Smooth Bedrock (Fabric) 1.1.3 soulbound: Soulbound 1.0.1 soulshards: Soul Shards Respawn 1.0.8 superores: Super Ores 2.0.1 theoneprobe: The One Probe 1.4.29.beta torcherino: Torcherino 1.8.49 trapexpansion: Trap Expansion 1.1.0 trees-do-not-float: Trees Do Not Float 1.1.1+build.23 tweakeroo: Tweakeroo 0.9.6 vanilla-hammers: Vanilla Hammers 1.4.1 voxelmap: VoxelMap 1.9.5 Launched Version: MultiMC5 LWJGL: 3.2.2 build 10 OpenGL: NO CONTEXT GL Caps:  Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric' Type: Client (map_client.txt) Resource Packs: ~~ERROR~~ NullPointerException: null Current Language: ~~ERROR~~ NullPointerException: null CPU: <unknown>

 `

**Comment by MrPurple6411** [comment]
was looking thew the coding trying to see if i could fix it for myself and it looks like they have changed a few things...... Gamerules system is all changed so that whole part isnt working aswell as BoundingBox class in minecraft is gone. 
edit nope just renamed to just Box
Hrmm chat systems changed too

**Comment by MrPurple6814** [comment]
And looks like a rework of the chat system too

**Comment by TehNut** [comment]
The only change is `GameRules#getKeys()` not existing anymore. Everything else is mapping changes. I've already begun the migration locally.

**Comment by TehNut** [comment]
Fixed by https://github.com/TehNut/Soul-Shards-Respawn/commit/0ba9e6807c8a7a8db30a103969174d0e15f27b48
