### ISSUE TITLE
Crash when putting soul stealer on vile sword

### ISSUE THREAD

**Issue by Vanroden141** [TehNut-Mods/Soul-Shards-Respawn#27]
Server crashes when using anvil to put soul stealer on vile sword, does not crash with other swords

[crash-2019-07-11_11.08.45-server.txt](https://github.com/TehNut/Soul-Shards-Respawn/files/3382696/crash-2019-07-11_11.08.45-server.txt)

**Comment by TehNut** [comment]
Not really sure what's causing this. For some reason a client method I never deal with is being called by my repair ingredient getter

**Comment by Vanroden141** [comment]
i just tested this crash in another clean instance and world with no other mods and it didnt happen, i will add in mods i have one at a time and get back to you with the results

Edit: I decided to confirm the crash still happens on my main client, turns out it doesnt crash in singleplayer but it still crashes on the server, so i dont think its another mod causing it

**Comment by TehNut** [comment]
Ok this happens with any enchantment being applied to the Vile Sword. Apparently at some point `Ingredient.ofStacks(ItemStack...)` was changed to be a client only method (mojang pls).
