### ISSUE TITLE
Enhancement: Allow transferring souls between shards

### ISSUE THREAD

**Issue by rapus95** [TehNut-Mods/Soul-Shards-Respawn#35]
As I multiple times accidentally bound two shards at the same time (having both in hotbar) it would be nice to be able to transfer the soul of one to the other. That would also allow it to efficiently farm single types of mobs in multiplayer (everyone killing what he finds)

**Comment by TehNut** [comment]
You can already combine shards of the same mob in an anvil.

**Comment by rapus95** [comment]
That means I'm always "wasting" a shard when splitting up work?

**Comment by rapus95** [comment]
@TehNut I tried it (being on 1.0.11 for fabric) and it doesn't work:
![2019-09-17_23 05 46](https://user-images.githubusercontent.com/5960902/65079715-1281c500-d9a0-11e9-9215-cde1bee28a36.png)
I checked twice. Both shards are for skeletons. Neither same nor different owner worked.

**Comment by TehNut** [comment]
I seem to have never implemented shard combination on the Fabric version
