### ISSUE TITLE
[BUG] using mending on the vile sword breaks all soul shards for a world

### ISSUE THREAD

**Issue by zzBuilderzz** [TehNut-Mods/Soul-Shards-Respawn#6]
I just ran into the weirdest bug. I was killing some golden cows (a mob from another mod) with my vile sword that I enchanted with soul stealer 5, sharpness 5 and unbreaking 3. Everything was work fine I was getting seven souls per kill, souls were being added, the tier went when the numbers reached a certain point...But then I noticed my sword was at half durability so I hoed into creative, spawned me an anvil and a mending enchantment book. After I added mending to the sword I went back to killing the cows and I repaired my vile sword with the experience that I gained...... but then I noticed that soul shard wasn't filling up.... so I grabbed another one out of creative, enchanted it with soul stealer 5, sharpness 5 and unbreaking 3... still no souls being added....I tried my other soul shard with golden cow souls on it (I was using a tier 2 soul shard in a soul cage spawner from this mod as I realized that would be faster than using two vanilla spawners with torcherino's on them) still no dice. I even spawned a completely new unbound soul shard... still no dice....I even left the world and got back in...still no dice

**Comment by TehNut** [comment]
So, wait, you were killing entities spawned by the Soul Cage? Do you have `countCageBornForShard` enabled in the config?

**Comment by zzBuilderzz** [comment]
wait what

**Comment by zzBuilderzz** [comment]
there's a config for that

**Comment by zzBuilderzz** [comment]
doh

**Comment by TehNut** [comment]
By default, you cannot build up a shard's soul count by using entities spawned by a cage.

**Comment by zzBuilderzz** [comment]
thanks for pointing that out
