### ISSUE TITLE
Crash on killing entity

### ISSUE THREAD

**Issue by axieum** [TehNut-Mods/Soul-Shards-Respawn#8]
Created a new world, summoned a zombie with commands, and killed it while in Creative Mode with a Vile Sword. Game crashed on killing it:

Crash-log: https://hastebin.com/uqamerurox.log
Config: https://hastebin.com/pihobozehi.cfg
Tiers: https://hastebin.com/seponubufi.json
MultiBlock: https://hastebin.com/ocekamiqec.json

**Comment by TehNut** [comment]
You deleted the default tier which should have a kill requirement of 0. Add that.
